name: Podman - E2E Test
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - "main"
jobs:
  upload-test-image:
    runs-on: ubuntu-latest
    steps:
      - name: Build test image
        run: |
          podman build -t test_image:${{ github.run_id }} -<<EOF
            FROM busybox
            RUN touch abc.txt
          EOF

      - name: Upload image
        uses: ishworkh/container-image-artifact-upload@update_dependencies
        with:
          image: "test_image:${{ github.run_id }}"
          container_engine: "podman"

  run-e2e-test:
    needs: upload-test-image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Download image
        uses: ./
        with:
          image: "test_image:${{ github.run_id }}"
          container_engine: "podman"

      - name: Test podman image is present
        run: |
          podman image inspect test_image:${{ github.run_id }}
