name: Podman - E2E Download Image From Another Workflow
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - "main"
jobs:
  call_e2e_from_workflow:
    uses: ./.github/workflows/e2e-from-workflow.yaml
    with:
      engine: "podman"
    secrets: inherit
