name: Podman - E2E Test
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - "main"
jobs:
  call-e2e-test:
    uses: ./.github/workflows/e2e.yaml
    with:
      engine: "podman"
    secrets: inherit
